// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_gQvSzA5HG3l_swwGWOQ6UvveLHyA6E',
    appId: '1:176579953271:web:587eff6eff7f9ae1ddfc72',
    messagingSenderId: '176579953271',
    projectId: 'promove-uff',
    authDomain: 'promove-uff.firebaseapp.com',
    storageBucket: 'promove-uff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAo3-v_4LNjCdXIj6cz1ReF1vvyXlll4',
    appId: '1:176579953271:android:f1a3b52b308f4c54ddfc72',
    messagingSenderId: '176579953271',
    projectId: 'promove-uff',
    storageBucket: 'promove-uff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8D2GfYVk1oK61y_WLR-MBfz6RBj5CPs',
    appId: '1:176579953271:ios:00315fc13fcb8b70ddfc72',
    messagingSenderId: '176579953271',
    projectId: 'promove-uff',
    storageBucket: 'promove-uff.appspot.com',
    iosClientId: '176579953271-fono8m08m9pav5p6urt5ag135miq84jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8D2GfYVk1oK61y_WLR-MBfz6RBj5CPs',
    appId: '1:176579953271:ios:00315fc13fcb8b70ddfc72',
    messagingSenderId: '176579953271',
    projectId: 'promove-uff',
    storageBucket: 'promove-uff.appspot.com',
    iosClientId: '176579953271-fono8m08m9pav5p6urt5ag135miq84jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_gQvSzA5HG3l_swwGWOQ6UvveLHyA6E',
    appId: '1:176579953271:web:b9bd23a8b13faec3ddfc72',
    messagingSenderId: '176579953271',
    projectId: 'promove-uff',
    authDomain: 'promove-uff.firebaseapp.com',
    storageBucket: 'promove-uff.appspot.com',
  );
}
